30 adding comment component
it-at-m/muc-patternlab-vue pull request #36
Opened 2024-04-22 11:49 UTC by langehm

Issues #30

2024-04-29 06:53 UTC, langehm commented
If the specialized component with text only is needed, the variant type needs to be extracted from the component into a separate file.

2024-04-30 08:39 UTC, FabianWilms requested changes
Sauber, gefällt mir sehr gut. Habe noch mit einem Commit die fehlenden Font-Definitionen ergänzt - das war mein Fehler.

2024-04-30 08:39 UTC, FabianWilms commented on docs/components/muc-comment.md
> +| rating  | number      |         | Number of stars to be displayed.                                          |
```suggestion
| rating  | number (float)     |         | Number of stars to be displayed.                                          |
```

2024-04-30 08:39 UTC, FabianWilms commented on docs/components/muc-comment.md
> +| variant | CommentType | listing | Choose the variant of the comment. This can be either slider oder listing |
```suggestion
| variant | CommentType | `listing` | Choose the variant of the comment. This can be either `slider` oder `listing` |
```

2024-04-30 08:39 UTC, FabianWilms commented on src/components/Comment/MucComment.vue
> +          :aria-label="`Rating: ${rating} out of ${MAX_STARS} stars`"
```suggestion
          :aria-label="`Bewertung: ${rating} von ${MAX_STARS} Sternen`"
```

VwVfG § 23 Abs. 1

2024-04-30 08:39 UTC, FabianWilms commented on docs/components/muc-comment.md
> +The muc-commment component can be used to display a comment in e.g. a chat.
Eine Erklärung, wann man muc-comment und wann muc-comment-text einsetzen soll/kann wäre noch super.

2024-05-02 09:24 UTC, merged